const names = [
  'Aaran',
  'Aaren',
  'Aarez',
  'Aarman',
  'Aaron',
  'Aaron-James',
  'Aarron',
  'Aaryan',
  'Aaryn',
  'Aayan',
  'Aazaan',
  'Abaan',
  'Abbas',
  'Abdallah',
  'Abdalroof',
  'Abdihakim',
  'Abdirahman',
  'Abdisalam',
  'Abdul',
  'Abdul-Aziz',
  'Abdulbasir',
  'Abdulkadir',
  'Abdulkarem',
  'Smith',
  'Jones',
  'Coollastname',
  'enter_name_here',
  'Ze',
  'Zechariah',
  'Zeek',
  'Zeeshan',
  'Zeid',
  'Zein',
  'Zen',
  'Zendel',
  'Zenith',
  'Zennon',
  'Zeph',
  'Zerah',
  'Zhen',
  'Zhi',
  'Zhong',
  'Zhuo',
  'Zi',
  'Zidane',
  'Zijie',
  'Zinedine',
  'Zion',
  'Zishan',
  'Ziya',
  'Ziyaan',
  'Zohaib',
  'Zohair',
  'Zoubaeir',
  'Zubair',
  'Zubayr',
  'Zuriel',
  'Xander',
  'Jared',
  'Courtney',
  'Gillian',
  'Clark',
  'Jared',
  'Grace',
  'Kelsey',
  'Tamar',
  'Alex',
  'Mark',
  'Tamar',
  'Farish',
  'Sarah',
  'Nathaniel',
  'Parker',
];

const thoughts = [
  "The sun sets, and I feel at peace",
  "A cup of coffee makes everything better.",
"Change is the only constant.",
"Just breathe, everything will be fine.",
"Every day is a fresh start.",
"Small steps lead to big changes.",
"Gratitude turns what we have into enough.",
"Life is about balance.",
"Inhale confidence, exhale doubt.",
"Time flies, but memories last forever.",
"Dream big, start small.",
"Kindness is always a choice.",
"Challenges are opportunities in disguise.",
"Happiness is found in little moments.",
"Take it one day at a time.",
"Adventure is out there, go find it.",
"Everything happens for a reason.",
"Focus on the good, let go of the bad.",
"Patience is the key to success.",
"Be the reason someone smiles today.",
];

// const friends = [
//   "John Doe",
// "Jane Smith",
// "Alex Brown",
// "Emily Davis",
// "Chris Johnson",
// "Sarah Wilson",
// "Michael Lee",
// "Laura Green",
// "Daniel Clark",
// "Jessica Miller",
// "David Young",
// "Olivia Harris",
// "Ethan Martinez",
// "Sophia Anderson",
// "Noah King",
// "Lily Thompson",
// "James White",
// "Mia Turner",
// "Henry Walker",
// "Ava Hall",
// ];

const reactions = [
  "Great thought!",
"I totally agree.",
"Well said!",
"That's interesting.",
"Nice perspective!",
"I hadnt thought of it that way.",
"Good point.",
"I love this!",
"Very insightful.",
"This made my day.",
"Absolutely!",
"Couldn't agree more.",
"Wow, so true.",
"This is brilliant.",
"Such a great idea.",
"I'm inspired!",
"So relatable!",
"Well written.",
"This made me think.",
"Incredible!",
];
// Get a random item given an array
export const getRandomArrItem = (arr: any) => arr[Math.floor(Math.random() * arr.length)];

// Gets a random full name
export const getRandomName =() =>
  `${getRandomArrItem(names)} ${getRandomArrItem(names)}`;

export const getRandomThought = () =>
  `${getRandomArrItem(thoughts)}`;

// export const getRandomFriend = () =>
//   `${getRandomArrItem(friends)}`;

export const getRandomReaction = () =>
  `${getRandomArrItem(reactions)}`;

